services:
  discord-bot:
    build: .
    container_name: discord-bot
    restart: unless-stopped
    volumes:
      - ./src:/usr/src/app/src
      - ./config.json:/usr/src/app/config.json
    command: [ 'pnpm', 'run', 'dev' ]
