name: Auto-Close Resolved Discussions

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday

jobs:
  close-resolved:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch resolved discussions
        uses: actions/github-script@v6
        with:
          script: |
            const { data: discussions } = await github.rest.discussions.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            let closedCount = 0;
            for (const discussion of discussions) {
              if (discussion.state === 'open' && discussion.answer_html_url) {
                await github.rest.discussions.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  discussion_number: discussion.number,
                  state: 'closed',
                });
                closedCount++;
              }
            }

            console.log(`✅ Closed ${closedCount} resolved discussions.`);
