name: Auto-Close Resolved Discussions

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday

jobs:
  close-resolved:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Close resolved discussions
        uses: actions/github-script@v6
        with:
          script: |
            const query = `
              query ($owner: String!, $repo: String!) {
                repository(owner: $owner, name: $repo) {
                  discussions(first: 100, states: OPEN) {
                    nodes {
                      id
                      number
                      title
                      answer {
                        id
                      }
                    }
                  }
                }
              }
            `;

            const variables = {
              owner: context.repo.owner,
              repo: context.repo.repo,
            };

            const response = await github.graphql(query, variables);
            const discussions = response.repository.discussions.nodes;
            let closedCount = 0;

            for (const discussion of discussions) {
              if (discussion.answer) {
                await github.rest.teams.updateDiscussion({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  discussion_number: discussion.number,
                  state: 'closed',
                });
                closedCount++;
              }
            }

            console.log(`✅ Closed ${closedCount} resolved discussions.`);
