name: Moderation

on:
  discussion:
    types: [created, edited]

jobs:
  moderate-content:
    runs-on: ubuntu-latest

    steps:
      - name: Check for inappropriate content
        uses: actions/github-script@v6
        env:
          PERSPECTIVE_API_KEY: ${{ secrets.PERSPECTIVE_API_KEY || '' }}
        with:
          script: |
            const axios = require('axios');

            const inappropriateWords = ['spam', 'harassment', 'abuse'];
            const content = context.payload.discussion.body || '';

            // Check against predefined word list
            if (inappropriateWords.some(word => content.toLowerCase().includes(word))) {
              core.setFailed('Inappropriate content detected based on word list. Please edit your discussion.');
              return;
            }

            // Use Perspective API to check for toxicity
            const response = await axios.post(
              'https://commentanalyzer.googleapis.com/v1alpha1/comments:analyze?key=' + process.env.PERSPECTIVE_API_KEY,
              {
                comment: { text: content },
                languages: ['en'],
                requestedAttributes: { TOXICITY: {} }
              }
            );

            const toxicityScore = response.data.attributeScores.TOXICITY.summaryScore.value;

            if (toxicityScore >= 0.8) {
              core.setFailed('Inappropriate content detected based on toxicity score. Please edit your discussion.');
            } else {
              console.log('✅ Content passed moderation.');
            }
