name: Welcome New Contributors

on:
  discussion:
    types: [created]

jobs:
  welcome:
    runs-on: ubuntu-latest

    steps:
      - name: Welcome first-time contributors
        uses: actions/github-script@v6
        with:
          script: |
            const discussion = context.payload.discussion;
            const isFirstDiscussion = discussion.author_association === 'FIRST_TIMER';

            if (isFirstDiscussion) {
              const welcomeMessage = `
                👋 Welcome @${discussion.user.login} to the **Create Nolly CLI Community**! 🎉

                We're excited to have you here. Here are some ways to get started:
                - 💬 Ask questions or share ideas in the [Q&A](https://github.com/thenolle/create-nolly/discussions/categories/questions-answers).
                - 🚀 Share your suggestions in the [Ideas](https://github.com/thenolle/create-nolly/discussions/categories/ideas-proposals).
                - 🌟 Don't forget to star the repo if you find it useful!

                If you need any help, feel free to ask. Happy hacking! 🚀
              `;
              await github.rest.issues.createComment({
                issue_number: discussion.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: welcomeMessage,
              });
            }
